"""Add Clinic+ comprehensive modules - scheduling, billing, prescribing, pharmacy, insurance, professional, RPM, emergency

Revision ID: 099b66af1227
Revises: 391511b6b078
Create Date: 2025-11-30 05:47:58.048054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099b66af1227'
down_revision = '391511b6b078'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_codes_code'), 'billing_codes', ['code'], unique=False)
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rxnorm_code', sa.String(length=50), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('drug_class', sa.String(length=100), nullable=True),
    sa.Column('drug_subclass', sa.String(length=100), nullable=True),
    sa.Column('dosage_form', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('is_controlled', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_rxnorm_code'), 'drugs', ['rxnorm_code'], unique=True)
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('coverage_description', sa.Text(), nullable=True),
    sa.Column('max_family_size', sa.Integer(), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('premium_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('premium_frequency', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plans_plan_id'), 'insurance_plans', ['plan_id'], unique=True)
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.String(length=50), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('pharmacy_type', sa.String(length=50), nullable=True),
    sa.Column('npi_number', sa.String(length=20), nullable=True),
    sa.Column('dea_number', sa.String(length=20), nullable=True),
    sa.Column('is_affiliated', sa.Boolean(), nullable=True),
    sa.Column('affiliation_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_pharmacy_id'), 'pharmacies', ['pharmacy_id'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('appointment_type', sa.String(length=50), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('parent_appointment_id', sa.Integer(), nullable=True),
    sa.Column('reminder_sent_sms', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_email', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['checked_in_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['parent_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_id'), 'appointments', ['appointment_id'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_format', sa.String(length=20), nullable=True),
    sa.Column('total_charge_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=50), nullable=True),
    sa.Column('subscriber_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('edi_file_path', sa.String(length=500), nullable=True),
    sa.Column('edi_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('response_code', sa.String(length=50), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('adjustment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=True)
    op.create_table('drug_allergy_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug1_id', sa.Integer(), nullable=False),
    sa.Column('drug2_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug1_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug2_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('clinic_plus_id', sa.String(length=50), nullable=True),
    sa.Column('identification_method', sa.String(length=50), nullable=False),
    sa.Column('emergency_type', sa.String(length=50), nullable=True),
    sa.Column('incident_location', sa.String(length=200), nullable=True),
    sa.Column('incident_latitude', sa.Float(), nullable=True),
    sa.Column('incident_longitude', sa.Float(), nullable=True),
    sa.Column('responder_id', sa.Integer(), nullable=True),
    sa.Column('responder_name', sa.String(length=200), nullable=True),
    sa.Column('responder_type', sa.String(length=50), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('data_accessed', sa.Text(), nullable=True),
    sa.Column('destination_facility_id', sa.Integer(), nullable=True),
    sa.Column('handoff_sent', sa.Boolean(), nullable=True),
    sa.Column('handoff_sent_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_accesses_access_id'), 'emergency_accesses', ['access_id'], unique=True)
    op.create_index(op.f('ix_emergency_accesses_clinic_plus_id'), 'emergency_accesses', ['clinic_plus_id'], unique=False)
    op.create_table('ems_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('device_serial_number', sa.String(length=100), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_serial_number')
    )
    op.create_index(op.f('ix_ems_devices_device_id'), 'ems_devices', ['device_id'], unique=True)
    op.create_table('fee_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('schedule_name', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.String(length=50), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('covered_members', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('premium_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('next_payment_due_date', sa.Date(), nullable=True),
    sa.Column('total_claims', sa.Integer(), nullable=True),
    sa.Column('total_claim_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remaining_coverage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_subscriptions_subscription_id'), 'insurance_subscriptions', ['subscription_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
    op.create_table('pharmacy_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('credential_number', sa.String(length=100), nullable=False),
    sa.Column('issuing_authority', sa.String(length=200), nullable=False),
    sa.Column('issuing_state', sa.String(length=50), nullable=True),
    sa.Column('issuing_country', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_credentials_credential_id'), 'professional_credentials', ['credential_id'], unique=True)
    op.create_table('professional_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('token_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('subscription_start', sa.Date(), nullable=False),
    sa.Column('subscription_end', sa.Date(), nullable=False),
    sa.Column('features_enabled', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_tokens_token_id'), 'professional_tokens', ['token_id'], unique=True)
    op.create_table('provider_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('appointment_duration', sa.Integer(), nullable=True),
    sa.Column('break_times', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpm_alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('vital_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_min', sa.Integer(), nullable=True),
    sa.Column('threshold_max', sa.Integer(), nullable=True),
    sa.Column('alert_level', sa.Integer(), nullable=True),
    sa.Column('notify_provider', sa.Boolean(), nullable=True),
    sa.Column('notify_emergency_contacts', sa.Boolean(), nullable=True),
    sa.Column('notify_emergency_response', sa.Boolean(), nullable=True),
    sa.Column('assigned_provider_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpm_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('device_serial_number', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_paired', sa.Boolean(), nullable=True),
    sa.Column('paired_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('battery_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_serial_number')
    )
    op.create_index(op.f('ix_rpm_devices_device_id'), 'rpm_devices', ['device_id'], unique=True)
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_payments', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_adjustments', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_statement_id'), 'statements', ['statement_id'], unique=True)
    op.create_table('charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('charge_date', sa.Date(), nullable=False),
    sa.Column('billing_code_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billing_code_id'], ['billing_codes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_charge_id'), 'charges', ['charge_id'], unique=True)
    op.create_table('credential_verification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=50), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_source', sa.String(length=100), nullable=True),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['professional_credentials.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_verification_logs_log_id'), 'credential_verification_logs', ['log_id'], unique=True)
    op.create_table('emergency_data_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_access_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.Boolean(), nullable=True),
    sa.Column('genotype', sa.Boolean(), nullable=True),
    sa.Column('allergies', sa.Boolean(), nullable=True),
    sa.Column('current_medications', sa.Boolean(), nullable=True),
    sa.Column('medical_history', sa.Boolean(), nullable=True),
    sa.Column('emergency_contacts', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emergency_access_id'], ['emergency_accesses.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_schedule_id', sa.Integer(), nullable=False),
    sa.Column('billing_code_id', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['billing_code_id'], ['billing_codes.id'], ),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['fee_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_handoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handoff_id', sa.String(length=50), nullable=False),
    sa.Column('emergency_access_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('source_facility_id', sa.Integer(), nullable=True),
    sa.Column('destination_facility_id', sa.Integer(), nullable=False),
    sa.Column('patient_condition', sa.Text(), nullable=True),
    sa.Column('vital_signs_summary', sa.Text(), nullable=True),
    sa.Column('interventions_provided', sa.Text(), nullable=True),
    sa.Column('medications_given', sa.Text(), nullable=True),
    sa.Column('incident_time', sa.DateTime(), nullable=True),
    sa.Column('dispatch_time', sa.DateTime(), nullable=True),
    sa.Column('estimated_arrival_time', sa.DateTime(), nullable=False),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['destination_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['emergency_access_id'], ['emergency_accesses.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_handoffs_handoff_id'), 'hospital_handoffs', ['handoff_id'], unique=True)
    op.create_table('insurance_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=50), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('copay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['insurance_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_claim_id'), 'insurance_claims', ['claim_id'], unique=True)
    op.create_table('insurance_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('coverage_start_date', sa.Date(), nullable=False),
    sa.Column('coverage_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['insurance_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_payments_payment_id'), 'insurance_payments', ['payment_id'], unique=True)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('rxnorm_code', sa.String(length=50), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('refills', sa.Integer(), nullable=True),
    sa.Column('refills_remaining', sa.Integer(), nullable=True),
    sa.Column('sig', sa.Text(), nullable=True),
    sa.Column('patient_instructions', sa.Text(), nullable=True),
    sa.Column('prescribed_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('filled_date', sa.Date(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('drug_interaction_checked', sa.Boolean(), nullable=True),
    sa.Column('allergy_checked', sa.Boolean(), nullable=True),
    sa.Column('interaction_warnings', sa.Text(), nullable=True),
    sa.Column('dea_required', sa.Boolean(), nullable=True),
    sa.Column('dea_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_prescription_id'), 'prescriptions', ['prescription_id'], unique=True)
    op.create_table('professional_token_renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('renewal_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('new_subscription_start', sa.Date(), nullable=False),
    sa.Column('new_subscription_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['professional_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('queue_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_provider_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['assigned_provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_entries_queue_id'), 'queue_entries', ['queue_id'], unique=True)
    op.create_table('rpm_vital_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Float(), nullable=True),
    sa.Column('measurement_method', sa.String(length=50), nullable=True),
    sa.Column('measurement_timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_timestamp', sa.DateTime(), nullable=True),
    sa.Column('signal_quality', sa.String(length=20), nullable=True),
    sa.Column('measurement_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['rpm_devices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpm_vital_readings_reading_id'), 'rpm_vital_readings', ['reading_id'], unique=True)
    op.create_table('telehealth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('meeting_id', sa.String(length=100), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telehealth_sessions_session_id'), 'telehealth_sessions', ['session_id'], unique=True)
    op.create_table('claim_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('procedure_code', sa.String(length=50), nullable=True),
    sa.Column('diagnosis_code', sa.String(length=50), nullable=True),
    sa.Column('charge_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passenger_accident_covers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_id', sa.String(length=50), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('trip_reference', sa.String(length=100), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('trip_origin', sa.String(length=200), nullable=True),
    sa.Column('trip_destination', sa.String(length=200), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coverage_start_time', sa.DateTime(), nullable=False),
    sa.Column('coverage_end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['insurance_claims.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passenger_accident_covers_cover_id'), 'passenger_accident_covers', ['cover_id'], unique=True)
    op.create_index(op.f('ix_passenger_accident_covers_trip_reference'), 'passenger_accident_covers', ['trip_reference'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription_fulfillments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_id', sa.String(length=50), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_date', sa.Date(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('verified_by_pharmacist', sa.Boolean(), nullable=True),
    sa.Column('pharmacist_id', sa.Integer(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_by_patient', sa.Boolean(), nullable=True),
    sa.Column('pickup_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_fulfillments_fulfillment_id'), 'prescription_fulfillments', ['fulfillment_id'], unique=True)
    op.create_table('prescription_refills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('refill_date', sa.Date(), nullable=False),
    sa.Column('refill_number', sa.Integer(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('dispensed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dispensed_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpm_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('alert_level', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('trigger_systolic_bp', sa.Integer(), nullable=True),
    sa.Column('trigger_diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('trigger_heart_rate', sa.Integer(), nullable=True),
    sa.Column('threshold_min', sa.Integer(), nullable=True),
    sa.Column('threshold_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('escalated_to_level', sa.Integer(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('emergency_contacts_notified', sa.Boolean(), nullable=True),
    sa.Column('emergency_response_dispatched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['rpm_devices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['rpm_vital_readings.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpm_alerts_alert_id'), 'rpm_alerts', ['alert_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpm_alerts_alert_id'), table_name='rpm_alerts')
    op.drop_table('rpm_alerts')
    op.drop_table('prescription_refills')
    op.drop_index(op.f('ix_prescription_fulfillments_fulfillment_id'), table_name='prescription_fulfillments')
    op.drop_table('prescription_fulfillments')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_passenger_accident_covers_trip_reference'), table_name='passenger_accident_covers')
    op.drop_index(op.f('ix_passenger_accident_covers_cover_id'), table_name='passenger_accident_covers')
    op.drop_table('passenger_accident_covers')
    op.drop_table('claim_items')
    op.drop_index(op.f('ix_telehealth_sessions_session_id'), table_name='telehealth_sessions')
    op.drop_table('telehealth_sessions')
    op.drop_index(op.f('ix_rpm_vital_readings_reading_id'), table_name='rpm_vital_readings')
    op.drop_table('rpm_vital_readings')
    op.drop_index(op.f('ix_queue_entries_queue_id'), table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_table('professional_token_renewals')
    op.drop_index(op.f('ix_prescriptions_prescription_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_insurance_payments_payment_id'), table_name='insurance_payments')
    op.drop_table('insurance_payments')
    op.drop_index(op.f('ix_insurance_claims_claim_id'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_index(op.f('ix_hospital_handoffs_handoff_id'), table_name='hospital_handoffs')
    op.drop_table('hospital_handoffs')
    op.drop_table('fee_schedule_items')
    op.drop_table('emergency_data_views')
    op.drop_index(op.f('ix_credential_verification_logs_log_id'), table_name='credential_verification_logs')
    op.drop_table('credential_verification_logs')
    op.drop_index(op.f('ix_charges_charge_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_statements_statement_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_rpm_devices_device_id'), table_name='rpm_devices')
    op.drop_table('rpm_devices')
    op.drop_table('rpm_alert_rules')
    op.drop_table('provider_schedules')
    op.drop_index(op.f('ix_professional_tokens_token_id'), table_name='professional_tokens')
    op.drop_table('professional_tokens')
    op.drop_index(op.f('ix_professional_credentials_credential_id'), table_name='professional_credentials')
    op.drop_table('professional_credentials')
    op.drop_table('pharmacy_inventory')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_insurance_subscriptions_subscription_id'), table_name='insurance_subscriptions')
    op.drop_table('insurance_subscriptions')
    op.drop_table('fee_schedules')
    op.drop_index(op.f('ix_ems_devices_device_id'), table_name='ems_devices')
    op.drop_table('ems_devices')
    op.drop_index(op.f('ix_emergency_accesses_clinic_plus_id'), table_name='emergency_accesses')
    op.drop_index(op.f('ix_emergency_accesses_access_id'), table_name='emergency_accesses')
    op.drop_table('emergency_accesses')
    op.drop_table('drug_interactions')
    op.drop_table('drug_allergy_interactions')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_appointments_appointment_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_pharmacies_pharmacy_id'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_insurance_plans_plan_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    op.drop_index(op.f('ix_drugs_rxnorm_code'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_billing_codes_code'), table_name='billing_codes')
    op.drop_table('billing_codes')
    # ### end Alembic commands ###
