"""Initial migration - create all tables

Revision ID: 391511b6b078
Revises: 
Create Date: 2025-11-30 05:41:06.546643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391511b6b078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
