"""Add organization management tables

Revision ID: 3c09d37646f8
Revises: ca5dbfae8f28
Create Date: 2025-11-30 06:30:40.012175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c09d37646f8'
down_revision = 'ca5dbfae8f28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding (for SQLite compatibility)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Add hcfa_file_path if it doesn't exist
    claims_columns = [col['name'] for col in inspector.get_columns('claims')]
    if 'hcfa_file_path' not in claims_columns:
        op.add_column('claims', sa.Column('hcfa_file_path', sa.String(length=500), nullable=True))
    
    # Add organization_id if it doesn't exist
    facilities_columns = [col['name'] for col in inspector.get_columns('facilities')]
    if 'organization_id' not in facilities_columns:
        # Use batch mode for SQLite to handle foreign key constraints
        with op.batch_alter_table('facilities', schema=None) as batch_op:
            batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
            # Check if foreign key already exists
            fks = [fk['name'] for fk in inspector.get_foreign_keys('facilities')]
            if 'fk_facilities_organization_id' not in fks:
                batch_op.create_foreign_key('fk_facilities_organization_id', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facilities', type_='foreignkey')
    op.drop_column('facilities', 'organization_id')
    op.drop_column('claims', 'hcfa_file_path')
    # ### end Alembic commands ###
