"""Add SOAP notes, physical exam, review of systems, and clinical reminders models

Revision ID: 40421d7293bf
Revises: 3c09d37646f8
Create Date: 2025-11-30 18:49:39.162746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40421d7293bf'
down_revision = '3c09d37646f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip foreign key creation for SQLite - will be handled in batch mode if needed
    # op.create_foreign_key(None, 'facilities', 'organizations', ['organization_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facilities', type_='foreignkey')
    # ### end Alembic commands ###
