"""Add Phase 2-4 models: Patient Portal, Documents, Messaging, Billing Tracker, ERA, UB-04, Care Plans, Treatment Plans

Revision ID: a1158ae841a2
Revises: insurance_companies_001
Create Date: 2025-11-30 19:24:48.279651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1158ae841a2'
down_revision = 'insurance_companies_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_plan_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=100), nullable=True),
    sa.Column('default_goals', sa.Text(), nullable=True),
    sa.Column('default_interventions', sa.Text(), nullable=True),
    sa.Column('default_review_frequency', sa.String(length=50), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('era_id', sa.String(length=50), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_received_date', sa.DateTime(), nullable=True),
    sa.Column('payer_name', sa.String(length=200), nullable=True),
    sa.Column('payer_tax_id', sa.String(length=50), nullable=True),
    sa.Column('payer_address', sa.Text(), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('check_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('total_claims', sa.Integer(), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_adjusted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_denied', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['insurance_companies.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eras_era_id'), 'eras', ['era_id'], unique=True)
    op.create_table('portal_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.String(length=50), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('status_history', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submission_method', sa.String(length=50), nullable=True),
    sa.Column('submission_reference', sa.String(length=100), nullable=True),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('payer_response_date', sa.DateTime(), nullable=True),
    sa.Column('payer_response_code', sa.String(length=50), nullable=True),
    sa.Column('payer_response_message', sa.Text(), nullable=True),
    sa.Column('expected_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('denial_code', sa.String(length=50), nullable=True),
    sa.Column('appeal_required', sa.Boolean(), nullable=True),
    sa.Column('appeal_submitted', sa.Boolean(), nullable=True),
    sa.Column('appeal_date', sa.Date(), nullable=True),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('last_followup_date', sa.Date(), nullable=True),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['insurance_companies.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_trackers_tracker_id'), 'billing_trackers', ['tracker_id'], unique=True)
    op.create_table('care_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=100), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('interventions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('review_frequency', sa.String(length=50), nullable=True),
    sa.Column('outcomes', sa.Text(), nullable=True),
    sa.Column('effectiveness_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_plans_care_plan_id'), 'care_plans', ['care_plan_id'], unique=True)
    op.create_table('era_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('era_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('claim_status', sa.String(length=50), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('patient_responsibility', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('adjustment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('denial_code', sa.String(length=50), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('service_date_from', sa.Date(), nullable=True),
    sa.Column('service_date_to', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['era_id'], ['eras.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_plan_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_goals', sa.Text(), nullable=True),
    sa.Column('treatment_approach', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('procedures', sa.Text(), nullable=True),
    sa.Column('therapies', sa.Text(), nullable=True),
    sa.Column('lifestyle_modifications', sa.Text(), nullable=True),
    sa.Column('patient_education', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_duration', sa.String(length=100), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_frequency', sa.String(length=50), nullable=True),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress_notes', sa.Text(), nullable=True),
    sa.Column('outcome_assessment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_treatment_plan_id'), 'treatment_plans', ['treatment_plan_id'], unique=True)
    op.create_table('ub04_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('statement_covers_period_from', sa.Date(), nullable=True),
    sa.Column('statement_covers_period_to', sa.Date(), nullable=True),
    sa.Column('patient_name', sa.String(length=200), nullable=True),
    sa.Column('patient_address', sa.Text(), nullable=True),
    sa.Column('patient_city', sa.String(length=100), nullable=True),
    sa.Column('patient_state', sa.String(length=50), nullable=True),
    sa.Column('patient_zip', sa.String(length=20), nullable=True),
    sa.Column('patient_dob', sa.Date(), nullable=True),
    sa.Column('patient_sex', sa.String(length=10), nullable=True),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('provider_npi', sa.String(length=20), nullable=True),
    sa.Column('provider_address', sa.Text(), nullable=True),
    sa.Column('provider_city', sa.String(length=100), nullable=True),
    sa.Column('provider_state', sa.String(length=50), nullable=True),
    sa.Column('provider_zip', sa.String(length=20), nullable=True),
    sa.Column('provider_tax_id', sa.String(length=50), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('admission_hour', sa.String(length=10), nullable=True),
    sa.Column('admission_type', sa.String(length=10), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('discharge_hour', sa.String(length=10), nullable=True),
    sa.Column('patient_status', sa.String(length=10), nullable=True),
    sa.Column('principal_diagnosis_code', sa.String(length=20), nullable=True),
    sa.Column('admitting_diagnosis_code', sa.String(length=20), nullable=True),
    sa.Column('other_diagnosis_codes', sa.Text(), nullable=True),
    sa.Column('procedure_codes', sa.Text(), nullable=True),
    sa.Column('revenue_codes', sa.Text(), nullable=True),
    sa.Column('primary_insurance_name', sa.String(length=200), nullable=True),
    sa.Column('primary_insurance_policy_number', sa.String(length=50), nullable=True),
    sa.Column('primary_insurance_group_number', sa.String(length=50), nullable=True),
    sa.Column('total_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ub04_forms_form_id'), 'ub04_forms', ['form_id'], unique=True)
    op.create_table('portal_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_from_patient', sa.Boolean(), nullable=True),
    sa.Column('related_appointment_id', sa.Integer(), nullable=True),
    sa.Column('related_prescription_id', sa.Integer(), nullable=True),
    sa.Column('related_lab_result_id', sa.Integer(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['related_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['related_lab_result_id'], ['lab_results.id'], ),
    sa.ForeignKeyConstraint(['related_prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip foreign key for SQLite - will be handled separately if needed
    # op.create_foreign_key(None, 'facilities', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facilities', type_='foreignkey')
    op.drop_table('portal_messages')
    op.drop_index(op.f('ix_ub04_forms_form_id'), table_name='ub04_forms')
    op.drop_table('ub04_forms')
    op.drop_index(op.f('ix_treatment_plans_treatment_plan_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_table('era_claims')
    op.drop_index(op.f('ix_care_plans_care_plan_id'), table_name='care_plans')
    op.drop_table('care_plans')
    op.drop_index(op.f('ix_billing_trackers_tracker_id'), table_name='billing_trackers')
    op.drop_table('billing_trackers')
    op.drop_table('portal_access_logs')
    op.drop_index(op.f('ix_eras_era_id'), table_name='eras')
    op.drop_table('eras')
    op.drop_table('care_plan_templates')
    # ### end Alembic commands ###
