"""Add CDS module tables

Revision ID: ca5dbfae8f28
Revises: 099b66af1227
Create Date: 2025-11-30 05:52:13.512527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5dbfae8f28'
down_revision = '099b66af1227'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
